<?php

// autoload_real.php generated by Composer

class ComposerAutoloaderInitab4d2db13291e6e65b449b2b21fcf290
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInitab4d2db13291e6e65b449b2b21fcf290', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader();
        spl_autoload_unregister(array('ComposerAutoloaderInitab4d2db13291e6e65b449b2b21fcf290', 'loadClassLoader'));

        $vendorDir = dirname(__DIR__);
        $baseDir = dirname($vendorDir);

        $includePaths = require __DIR__ . '/include_paths.php';
        array_push($includePaths, get_include_path());
        set_include_path(join(PATH_SEPARATOR, $includePaths));

        $map = require __DIR__ . '/autoload_namespaces.php';
        foreach ($map as $namespace => $path) {
            $loader->set($namespace, $path);
        }

        $classMap = require __DIR__ . '/autoload_classmap.php';
        if ($classMap) {
            $loader->addClassMap($classMap);
        }

        $loader->register(true);

        require $vendorDir . '/petrp/orm/php53/Orm/Orm.php';
        require $vendorDir . '/petrp/httpphpunit/HttpPHPUnit/init.php';
        require $vendorDir . '/petrp/access/Access/Init.php';
        require $vendorDir . '/texy/texy/src/texy.php';
        require $vendorDir . '/nette/nette/Nette/loader.php';

        return $loader;
    }
}
